using System.Security.Cryptography;

namespace NutManager.Core.Models;

/// <summary>
/// Identifies the small, fixed set of remote secrets owned by NutManager.
/// The persistent target name is generated by the platform store, never by callers.
/// </summary>
public enum RemoteCredentialKind
{
    SshPassword,
    SshPrivateKeyPassphrase,
    SmbPassword,

    /// <summary>
    /// The password of the alternate Windows account used to reach the NutManager agent.
    ///
    /// A separate kind, and therefore a separate stored target, even when the account happens to
    /// match the SMB one. The two authorize different things — one reads configuration files, the
    /// other controls a service — and a single stored secret would silently grant whichever
    /// boundary the operator did not think they were granting.
    /// </summary>
    WindowsAgentPassword
}

public enum RemoteCredentialStoreStatus
{
    Success,
    NotFound,
    Unsupported,
    AccessDenied,
    CredentialStoreUnavailable,
    Failed
}

public sealed class RemoteCredentialStoreResult
{
    public RemoteCredentialStoreResult(RemoteCredentialStoreStatus status, string? message = null)
    {
        Status = status;
        Message = message;
    }

    public RemoteCredentialStoreStatus Status { get; }

    public string? Message { get; }

    public bool IsSuccess => Status == RemoteCredentialStoreStatus.Success;
}

/// <summary>
/// A disposable copy of a protected remote secret. It intentionally exposes no
/// string conversion or observable secret property.
/// </summary>
public sealed class RemoteCredentialSecret : IDisposable
{
    private char[]? _buffer;

    public RemoteCredentialSecret(ReadOnlySpan<char> value)
    {
        if (value.IsEmpty)
        {
            throw new ArgumentException("A credential secret is required.", nameof(value));
        }

        _buffer = value.ToArray();
    }

    public ReadOnlyMemory<char> Memory => _buffer is null
        ? ReadOnlyMemory<char>.Empty
        : _buffer;

    public void Dispose()
    {
        var buffer = Interlocked.Exchange(ref _buffer, null);
        if (buffer is not null)
        {
            CryptographicOperations.ZeroMemory(System.Runtime.InteropServices.MemoryMarshal.AsBytes(buffer.AsSpan()));
        }
    }

    public override string ToString() => "RemoteCredentialSecret";
}

public sealed class RemoteCredentialReadResult : IDisposable
{
    public RemoteCredentialReadResult(RemoteCredentialStoreStatus status, RemoteCredentialSecret? secret = null, string? message = null)
    {
        Status = status;
        Secret = secret;
        Message = message;
    }

    public RemoteCredentialStoreStatus Status { get; }

    public RemoteCredentialSecret? Secret { get; }

    public string? Message { get; }

    public bool IsSuccess => Status == RemoteCredentialStoreStatus.Success && Secret is not null;

    public void Dispose() => Secret?.Dispose();
}
